# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c03226ea4931d1b496963a15ca83538fbde67681ea887bff70ab4430899889b2675e2811beea63f428eeb1d164fcc94e0fd96c27ffcfeda1fe16e8095c468ce

test:
  secret_key_base: 6e287101378ef17f38f1c4e13ec3183ea59c8d60d7b8f32ade70e15572076908203718766694c88f40593facc67a6964941ef59cfff68be4f0bd07df6d4e408f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
